[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

[fuzz]
runs = 100
seed = "0x02"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${RPC_MAINNET}"
tarp_testnet = "${RPC_TARP}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
