[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
# solc = "0.8.15"
evm_version = "cancun"

[lint]
lint_on_build = false  # Disable solar linter due to Core library import resolution issues

[fuzz]
runs = 100
seed = "0x02"

[rpc_endpoints]
# megaeth =
megatest = "https://timothy.megaeth.com/rpc"
megatest_alchemy = "https://megaeth-testnet.g.alchemy.com/v2/${ALCHEMY_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
