[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
# solc = "0.8.15"

[fuzz]
runs = 100
seed = "0x02"

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
tarp_testnet = "${RPC_TARP}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
