[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 100000 # Don't go higher or else Hyperevmscan cannot verify contracts
fs_permissions = [{ access = "read-write", path = "./"}]
# solc = "0.8.15"
# evm_version = "cancun"

[fuzz]
runs = 100

[rpc_endpoints]
hyperevm = "https://hyperliquid-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
hypertest = "https://hyperliquid-testnet.drpc.org"
#hypertest = "https://spectrum-01.simplystaking.xyz/hyperliquid-tn-rpc/evm"
#hypertest = "https://998.rpc.thirdweb.com"

